// Generated by scripts/import-leaderboard.mjs. Do not edit manually.

export interface ChallengeLeaderboardEntry {
  rank: number
  teamId: string
  teamName: string
  totalScore: number
}

export const challengeLeaderboardEntries = [
  {
    rank: 1,
    teamId: "T000012",
    teamName: "sota",
    totalScore: 92.37289954342617,
  },
  {
    rank: 2,
    teamId: "T000010",
    teamName: "Primotion",
    totalScore: 92.19324603152762,
  },
  {
    rank: 3,
    teamId: "T000015",
    teamName: "NPU-EAI",
    totalScore: 85.56472369370465,
  },
  {
    rank: 4,
    teamId: "T000022",
    teamName: "XJTU_Talent",
    totalScore: 85.4081892151743,
  },
  {
    rank: 5,
    teamId: "T000020",
    teamName: "hit-miao",
    totalScore: 85.12080971560738,
  },
  {
    rank: 6,
    teamId: "T000021",
    teamName: "cot4b_x2w_step60k",
    totalScore: 74.38451757806249,
  },
  {
    rank: 7,
    teamId: "T000018",
    teamName: "Northstar",
    totalScore: 69.17817863110619,
  },
  {
    rank: 8,
    teamId: "T000019",
    teamName: "PeaceVLA",
    totalScore: 56.79468275889551,
  },
  {
    rank: 9,
    teamId: "T000016",
    teamName: "Nova",
    totalScore: 51.38199473968168,
  },
  {
    rank: 10,
    teamId: "T000014",
    teamName: "Spark",
    totalScore: 50.75683078390648,
  },
  {
    rank: 11,
    teamId: "T000017",
    teamName: "JustTry",
    totalScore: 49.46441169355271,
  },
  {
    rank: 12,
    teamId: "T000011",
    teamName: "Horizon",
    totalScore: 48.118633605621966,
  },
  {
    rank: 13,
    teamId: "T000013",
    teamName: "RoboDeamers",
    totalScore: 47.42043671278776,
  },
  {
    rank: 14,
    teamId: "T000023",
    teamName: "ACTVisionOnly",
    totalScore: 35.43485146979003,
  },
  {
    rank: 15,
    teamId: "T000024",
    teamName: "longteam",
    totalScore: 19.880257879315934,
  },
] as const satisfies readonly ChallengeLeaderboardEntry[]
